"""
Generator Module - Formats analysis results for output

This module takes analysis results and formats them into
various output formats (Markdown, JSON, HTML, etc.)
"""

import json
from typing import Dict, Any, Optional
from datetime import datetime


class GeneratorError(Exception):
    """Custom exception for generator errors"""
    pass


def generate_markdown_report(analysis_result: Dict[str, Any], skill_url: Optional[str] = None) -> str:
    """
    Generate a Markdown-formatted report from analysis results.
    
    Args:
        analysis_result: Dictionary containing analysis data
        skill_url: Optional URL of the analyzed skill
    
    Returns:
        Formatted Markdown string
    """
    if not analysis_result.get('success'):
        raise GeneratorError("Analysis was not successful")
    
    report = []
    report.append("# AI Skill Analysis Report\n")
    report.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
    
    if skill_url:
        report.append(f"**Source:** {skill_url}\n")
    
    report.append(f"**Model Used:** {analysis_result.get('model_used', 'Unknown')}\n")
    
    # Token usage if available
    if 'tokens_used' in analysis_result:
        tokens = analysis_result['tokens_used']
        report.append(f"**Tokens:** {tokens.get('total_tokens', 'N/A')} (prompt: {tokens.get('prompt_tokens', 'N/A')}, completion: {tokens.get('completion_tokens', 'N/A')})\n")
    
    report.append("\n---\n")
    
    # Summary
    report.append("## 📋 Summary\n")
    report.append(f"{analysis_result.get('summary', 'No summary available')}\n")
    
    # Functionalities
    report.append("\n---\n")
    report.append("## ⚙️ Key Functionalities\n")
    functionalities = analysis_result.get('functionalities', [])
    if functionalities:
        for i, func in enumerate(functionalities, 1):
            report.append(f"{i}. {func}")
    else:
        report.append("*No functionalities extracted*")
    
    # Use Cases
    report.append("\n---\n")
    report.append("## 💡 Potential Use Cases\n")
    use_cases = analysis_result.get('use_cases', [])
    if use_cases:
        for i, case in enumerate(use_cases, 1):
            report.append(f"{i}. {case}")
    else:
        report.append("*No use cases extracted*")
    
    # Improvement Suggestions
    report.append("\n---\n")
    report.append("## 🚀 Improvement Suggestions\n")
    suggestions = analysis_result.get('improvement_suggestions', [])
    if suggestions:
        for i, suggestion in enumerate(suggestions, 1):
            report.append(f"{i}. {suggestion}")
    else:
        report.append("*No suggestions provided*")
    
    report.append("\n---\n")
    report.append("*Generated by AI Skill Insight Engine*\n")
    
    return "\n".join(report)


def generate_json_output(analysis_result: Dict[str, Any], skill_url: Optional[str] = None) -> str:
    """
    Generate a JSON-formatted output from analysis results.
    
    Args:
        analysis_result: Dictionary containing analysis data
        skill_url: Optional URL of the analyzed skill
    
    Returns:
        JSON string
    """
    output = {
        'metadata': {
            'generated_at': datetime.now().isoformat() + 'Z',
            'source_url': skill_url,
            'model_used': analysis_result.get('model_used', 'Unknown'),
            'tokens_used': analysis_result.get('tokens_used', {})
        },
        'analysis': {
            'summary': analysis_result.get('summary', ''),
            'functionalities': analysis_result.get('functionalities', []),
            'use_cases': analysis_result.get('use_cases', []),
            'improvement_suggestions': analysis_result.get('improvement_suggestions', [])
        },
        'success': analysis_result.get('success', False)
    }
    
    return json.dumps(output, indent=2, ensure_ascii=False)


def generate_html_report(analysis_result: Dict[str, Any], skill_url: Optional[str] = None) -> str:
    """
    Generate an HTML-formatted report from analysis results.
    
    Args:
        analysis_result: Dictionary containing analysis data
        skill_url: Optional URL of the analyzed skill
    
    Returns:
        HTML string
    """
    if not analysis_result.get('success'):
        raise GeneratorError("Analysis was not successful")
    
    html = []
    html.append("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Skill Analysis Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        .meta { background: #ecf0f1; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .section { margin: 20px 0; }
        ul { padding-left: 20px; }
        li { margin: 8px 0; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
""")
    
    html.append("<h1>🤖 AI Skill Analysis Report</h1>\n")
    
    # Metadata
    html.append('<div class="meta">')
    html.append(f"<p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>")
    if skill_url:
        html.append(f"<p><strong>Source:</strong> <a href='{skill_url}'>{skill_url}</a></p>")
    html.append(f"<p><strong>Model:</strong> {analysis_result.get('model_used', 'Unknown')}</p>")
    html.append('</div>\n')
    
    # Summary
    html.append('<h2>📋 Summary</h2>')
    html.append(f"<p>{analysis_result.get('summary', 'No summary available')}</p>\n")
    
    # Functionalities
    html.append('<h2>⚙️ Key Functionalities</h2>')
    html.append('<ul>')
    for func in analysis_result.get('functionalities', []):
        html.append(f"<li>{func}</li>")
    html.append('</ul>\n')
    
    # Use Cases
    html.append('<h2>💡 Potential Use Cases</h2>')
    html.append('<ul>')
    for case in analysis_result.get('use_cases', []):
        html.append(f"<li>{case}</li>")
    html.append('</ul>\n')
    
    # Improvement Suggestions
    html.append('<h2>🚀 Improvement Suggestions</h2>')
    html.append('<ul>')
    for suggestion in analysis_result.get('improvement_suggestions', []):
        html.append(f"<li>{suggestion}</li>")
    html.append('</ul>\n')
    
    html.append('<div class="footer">')
    html.append('<p><em>Generated by AI Skill Insight Engine</em></p>')
    html.append('</div>')
    html.append('</body></html>')
    
    return "\n".join(html)


def get_output_format(filename: str) -> str:
    """
    Determine output format from filename extension.
    
    Args:
        filename: Output filename
    
    Returns:
        Format string ('markdown', 'json', 'html')
    """
    if filename.endswith('.md'):
        return 'markdown'
    elif filename.endswith('.json'):
        return 'json'
    elif filename.endswith('.html'):
        return 'html'
    else:
        return 'markdown'  # Default


if __name__ == "__main__":
    # Test the generator
    test_result = {
        'success': True,
        'summary': 'This is a test skill for weather data.',
        'functionalities': ['Fetch weather data', 'Provide forecasts', 'Support multiple locations'],
        'use_cases': ['Personal weather tracking', 'Travel planning', 'Event planning'],
        'improvement_suggestions': ['Add severe weather alerts', 'Integrate with calendar apps'],
        'model_used': 'pollinations/gemini-search',
        'tokens_used': {'total_tokens': 150, 'prompt_tokens': 100, 'completion_tokens': 50}
    }
    
    print("=== Markdown Report ===")
    print(generate_markdown_report(test_result))
    
    print("\n=== JSON Output ===")
    print(generate_json_output(test_result))
